### ISSUE TITLE
Region Execution Failure

### ISSUE THREAD

**Issue by shravanthil** [awslabs/aws-iam-access-analyzer-policy-validation-config-rule#1]
Hi Team

We tried to run this on us-east-1 region, we were able successfully get the results.

Whereas us-west-2 region doesn't deploy the cloudformation modules and throws the error as at Policy Config Creation and Lambda Function with errors "Resource handler returned message: "Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: Lambda, Status Code: 400, Request ID: adcbcd33-c6d5-4f90-b70c-9297851be91c)" (RequestToken: 7ef2a0fa-974c-9780-9675-f2de52792b28, HandlerErrorCode: InvalidRequest)" and "The following resource(s) failed to create: [PolicyValidationConfigRuleFunction]. Rollback requested by user." respectivity. Note: Region changes made --parameter-overrides RegionToValidateGlobalResources='us-west-2' while execution.

**Comment by mluttrell** [comment]
Thanks for opening this issue.  The CloudFormation template references a bucket that hosts the packaged function and resides in us-east-1.  I'll work on making a copy available in all regions.

In the meantime, you can package the source code found in this repository and host it in your own S3 bucket in your desired regions.  Then you would update the S3 bucket references in the template:

```
PolicyValidationConfigRuleFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: policy-validation-config-rule
      Code:
        S3Bucket: **iam-access-analyzer-policy-validation-config-rule**
```
